name: 🔒 Auto-close Pull Requests

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "👋 This repository does not accept pull requests. Please contribute on [Weblate](https://hosted.weblate.org/projects/actualbudget/) instead."
